### ISSUE TITLE
Upgrade to ScribeJava 2.4.0

### ISSUE THREAD

**Issue by bdunn44** [ahn/vaadin-oauthpopup#10]
This library is quite behind the current ScribeJava release (1.3.7 vs 2.4.0), which has greatly expanded support for both OAuth 1.0a and 2.0. The ScribeJava API has been refactored to a large extent which will require significant change to this addon.

The latest ScribeJava API also adds functionality to control the standard OAuth parameters sent to services, which should be exposed through this addon to allow more flexibility to the user.

**Comment by bdunn44** [comment]
Created pull request #11 to resolve this issue. The demo has also been updated for this refactor and upgraded to Vaadin 7.6.4 (with Valo theme). This pull request also resolves issue #2 which has been added to the demo as well.

**Comment by ahn** [comment]
Sorry for being away. People should move to the fork by bdunn44: https://github.com/bdunn44/vaadin-oauthpopup

It's in Vaadin Directory, too: https://vaadin.com/directory#!addon/oauth2-popup-add-on

Added a description to README to point to the fork.
