### ISSUE TITLE
Pass OAuth2 access token raw response to the application

### ISSUE THREAD

**Issue by livotov** [ahn/vaadin-oauthpopup#4]
When OAuth completes, vaadin-oauthpopup takes only access token and secret from the OAuth response. However, the entire response may also contain some usefu lidentification data, such as user-id or e-mail - this can be very handy for the target vaadin application.

**Comment by tkachleo** [comment]
Hey, can you update the jar in maven? the version there is 0.0.3, and it doesn't contain this fix.
Also im wondering, the raw response is a string. what does it contain and how? is it json or something?
For now I'm trying to get the name of the user and his profile picture. Does this string have this information?
Thanks.

**Comment by ahn** [comment]
Updated. Version 0.0.4 in Vaadin Directory.

I think what the raw response string contains is different for different services (twitter, facebook, ...)
